language: ruby
rvm:
  - 1.8.7
  - jruby-18mode # JRuby in 1.8 mode

jdk:
  - oraclejdk7
  - oraclejdk6

before_script:
  - mysql -e "create database petstore_test;"
  - mysql -e "create user 'testbot'@'localhost' identified by 'petstore'";
  - mysql -u root -e "grant all on petstore_test.* to 'testbot'@'localhost'";

script: bundle exec buildr clean install