defaults: &defaults
  jdbc.driverClassName: com.mysql.jdbc.Driver
  hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  test.log.file: test.log
  test.jdbc.driverClassName: com.mysql.jdbc.Driver
  test.jdbc.url: jdbc:mysql://localhost:3306/petstore-test
  test.jdbc.username: testbot
  test.jdbc.password: petstore
  test.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  test.timeServer.port: 10013

development:
  filter:
    <<: *defaults