defaults: &defaults
  test.log.file: test.log
  test.jdbc.driverClassName: com.mysql.jdbc.Driver
  test.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  test.jdbc.url: jdbc:mysql://localhost:3306/petstore-test
  test.jdbc.username: testbot
  test.jdbc.password: petstore
  test.timeServer.port: 10013
  test.server.host: localhost
  test.jdbc.password: petstore
  jdbc.driverClassName: com.mysql.jdbc.Driver
  hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  
development:
  filter:
    <<: *defaults
    jdbc.url: jdbc:mysql://localhost:3306/petstore-dev
    jdbc.username: petstore
    jdbc.password: petstore
    context.path: /petstore
    log.file: development.log    
    test.server.port: 8090
  server.port: 8090    
  
production:
  filter:
    <<: *defaults
    jdbc.url: jdbc:mysql://localhost:3306/petstore-prod
    jdbc.username: sysadmin
    jdbc.password: petstore
    context.path: /petstore
    test.server.port: 80
    log.file: production.log
    timeServer.host: time.nist.gov
    timeServer.port: 13  
  server.port: 80
  
integration:
  filter:
    <<: *defaults
    jdbc.url: jdbc:mysql://localhost:3306/petstore-edge
    jdbc.username: integrator
    jdbc.password: petstore
    context.path: /petstore
    test.server.port: 8000
    log.file: integration.log
    timeServer.host: localhost
    timeServer.port: 10000    
  server.port: 8000  